import type { AppContent } from './types'

export const en: AppContent = {
  shell: {
    navOperations: 'Operations',
    navApiKeys: 'API keys',
    navSettings: 'Settings',
    signOut: 'Sign out',
    userLabel: 'Account',
  },
  statuses: {
    created: 'Created',
    pix_pending: 'Pix pending',
    pix_confirmed: 'Pix confirmed',
    settling: 'Settling',
    confirmed: 'Confirmed',
    failed: 'Failed',
  },
  operations: {
    title: 'Operations',
    description:
      'Buy MockUSDT with simulated Pix and receive it in your wallet on the Polygon Amoy test network.',
    newOperation: 'New operation',
    amountLabel: 'Amount in MockUSDT',
    receiverWalletLabel: 'Destination wallet (EVM)',
    requestIdHint: 'Retry identifier generated automatically to prevent duplicates.',
    requestIdLabel: 'Retry identifier',
    submit: 'Create operation',
    creating: 'Creating…',
    cancel: 'Cancel',
    empty: 'No operations yet. Create the first one to see the full flow.',
    emptyCta: 'Create operation',
    loading: 'Loading operations…',
    loadError: 'Could not load operations.',
    loadErrorCta: 'Try again',
    createError: 'Could not create the operation.',
    createErrorInvalidAmount: 'Enter an amount greater than zero, with at most 2 decimal places.',
    createErrorInvalidWallet: 'Invalid wallet. Use an EVM address with 40 hex characters (0x…).',
    confirmPix: "I've paid the Pix (simulated confirmation)",
    pixCode: 'Pix code (simulated copy-and-paste)',
    txHash: 'Amoy transaction',
    explorerLink: 'View on PolygonScan Amoy',
    senderWallet: 'Source wallet',
    receiverWallet: 'Destination wallet',
    errorDetail: 'Reason',
    pollingNote: 'Auto-refreshing…',
    copy: 'Copy',
    copied: 'Copied!',
    tableHeadAmount: 'Amount',
    tableHeadStatus: 'Status',
    tableHeadCreated: 'Created at',
    tableHeadToken: 'Token',
    errorInsufficientAmount: 'The amount entered is not allowed for this operation. Try a smaller amount.',
    errorServiceUnavailable: 'The service is temporarily unavailable. Please try again later.',
    errorReconciliation: 'We could not complete the operation automatically. Please try again later or contact support.',
    errorNotFound: 'Operation not found.',
    errorUnauthorized: 'You do not have permission to perform this action.',
    errorGeneric: 'Could not complete the operation. Please try again.',
  },
  apiKeys: {
    title: 'API keys',
    description:
      'Use keys to authenticate calls to sandbox functions from the command line or integrations.',
    nameLabel: 'Key name',
    create: 'Create key',
    submitCreate: 'Generate key',
    cancel: 'Cancel',
    empty: 'No keys created yet.',
    revealWarning: 'Copy it now: this key will not be shown again. Store it somewhere safe.',
    revoke: 'Revoke',
    revokeConfirm: 'Confirm revocation?',
    revokedChip: 'Revoked',
    activeChip: 'Active',
    headName: 'Name',
    headPrefix: 'Prefix',
    headCreated: 'Created at',
    headLastUsed: 'Last used',
    headActions: 'Actions',
    docsLink: 'See the documentation for usage examples.',
  },
  settings: {
    title: 'Settings',
    emailLabel: 'Account email',
    passwordTitle: 'Change password',
    newPasswordLabel: 'New password',
    confirmPasswordLabel: 'Confirm new password',
    savePassword: 'Save new password',
    successNotice: 'Password updated successfully.',
    mismatchError: 'Passwords do not match or are too short (minimum 8 characters).',
    genericError: 'Could not update the password.',
    signOut: 'Sign out',
  },
}
