import type { AppContent } from './types'

export const es: AppContent = {
  shell: {
    navOperations: 'Operaciones',
    navApiKeys: 'Claves de API',
    navSettings: 'Configuración',
    signOut: 'Salir',
    userLabel: 'Cuenta',
  },
  statuses: {
    created: 'Creada',
    pix_pending: 'Pix pendiente',
    pix_confirmed: 'Pix confirmado',
    settling: 'Liquidando',
    confirmed: 'Confirmada',
    failed: 'Falló',
  },
  operations: {
    title: 'Operaciones',
    description:
      'Compra MockUSDT con Pix simulado y recíbelo en tu billetera en la red de prueba Polygon Amoy.',
    newOperation: 'Nueva operación',
    amountLabel: 'Monto en MockUSDT',
    receiverWalletLabel: 'Billetera de destino (EVM)',
    requestIdHint: 'Identificador de repetición generado automáticamente para evitar duplicados.',
    submit: 'Crear operación',
    cancel: 'Cancelar',
    empty: 'Aún no hay operaciones. Crea la primera para ver el flujo completo.',
    emptyCta: 'Crear operación',
    loadError: 'No fue posible cargar las operaciones.',
    createError: 'No fue posible crear la operación.',
    confirmPix: 'Ya pagué el Pix (confirmación simulada)',
    pixCode: 'Código Pix (copia y pega simulado)',
    txHash: 'Transacción en Amoy',
    explorerLink: 'Ver en PolygonScan Amoy',
    senderWallet: 'Billetera de origen',
    receiverWallet: 'Billetera de destino',
    errorDetail: 'Detalle del error',
    pollingNote: 'Actualizando automáticamente…',
    copy: 'Copiar',
    copied: '¡Copiado!',
    tableHeadAmount: 'Monto',
    tableHeadStatus: 'Estado',
    tableHeadCreated: 'Creada el',
    tableHeadToken: 'Token',
  },
  apiKeys: {
    title: 'Claves de API',
    description:
      'Usa claves para autenticar llamadas a las funciones del sandbox por línea de comando o integraciones.',
    nameLabel: 'Nombre de la clave',
    create: 'Crear clave',
    submitCreate: 'Generar clave',
    cancel: 'Cancelar',
    empty: 'Aún no hay claves creadas.',
    revealWarning:
      'Cópiala ahora: esta clave no se mostrará nuevamente. Guárdala en un lugar seguro.',
    revoke: 'Revocar',
    revokeConfirm: '¿Confirmar revocación?',
    revokedChip: 'Revocada',
    activeChip: 'Activa',
    headName: 'Nombre',
    headPrefix: 'Prefijo',
    headCreated: 'Creada el',
    headLastUsed: 'Último uso',
    headActions: 'Acciones',
    docsLink: 'Consulta la documentación para ejemplos de uso.',
  },
  settings: {
    title: 'Configuración',
    emailLabel: 'Correo de la cuenta',
    passwordTitle: 'Cambiar contraseña',
    newPasswordLabel: 'Nueva contraseña',
    confirmPasswordLabel: 'Confirmar nueva contraseña',
    savePassword: 'Guardar nueva contraseña',
    successNotice: 'Contraseña actualizada con éxito.',
    mismatchError: 'Las contraseñas no coinciden o son demasiado cortas (mínimo 8 caracteres).',
    genericError: 'No fue posible actualizar la contraseña.',
    signOut: 'Cerrar sesión',
  },
}
