import type { AppContent } from './types'

export const pt: AppContent = {
  shell: {
    navOperations: 'Operações',
    navApiKeys: 'Chaves de API',
    navSettings: 'Configurações',
    signOut: 'Sair',
    userLabel: 'Conta',
  },
  statuses: {
    created: 'Criada',
    pix_pending: 'Pix pendente',
    pix_confirmed: 'Pix confirmado',
    settling: 'Liquidando',
    confirmed: 'Confirmada',
    failed: 'Falhou',
  },
  operations: {
    title: 'Operações',
    description:
      'Compre MockUSDT com Pix simulado e receba na sua carteira na rede de teste Polygon Amoy.',
    newOperation: 'Nova operação',
    amountLabel: 'Valor em MockUSDT',
    receiverWalletLabel: 'Carteira de destino (EVM)',
    requestIdHint: 'Identificador de repetição gerado automaticamente para evitar duplicidades.',
    submit: 'Criar operação',
    cancel: 'Cancelar',
    empty: 'Nenhuma operação ainda. Crie a primeira para ver o fluxo completo.',
    emptyCta: 'Criar operação',
    loading: 'Carregando operações…',
    loadError: 'Não foi possível carregar as operações.',
    loadErrorCta: 'Tentar novamente',
    createError: 'Não foi possível criar a operação.',
    confirmPix: 'Já paguei o Pix (confirmação simulada)',
    pixCode: 'Código Pix (copia e cola simulado)',
    txHash: 'Transação na Amoy',
    explorerLink: 'Ver no PolygonScan Amoy',
    senderWallet: 'Carteira de origem',
    receiverWallet: 'Carteira de destino',
    errorDetail: 'Detalhe do erro',
    pollingNote: 'Atualizando automaticamente…',
    copy: 'Copiar',
    copied: 'Copiado!',
    tableHeadAmount: 'Valor',
    tableHeadStatus: 'Status',
    tableHeadCreated: 'Criada em',
    tableHeadToken: 'Token',
  },
  apiKeys: {
    title: 'Chaves de API',
    description:
      'Use chaves para autenticar chamadas às funções do sandbox via linha de comando ou integrações.',
    nameLabel: 'Nome da chave',
    create: 'Criar chave',
    submitCreate: 'Gerar chave',
    cancel: 'Cancelar',
    empty: 'Nenhuma chave criada ainda.',
    revealWarning:
      'Copie agora: esta chave não será exibida novamente. Guarde-a em um local seguro.',
    revoke: 'Revogar',
    revokeConfirm: 'Confirmar revogação?',
    revokedChip: 'Revogada',
    activeChip: 'Ativa',
    headName: 'Nome',
    headPrefix: 'Prefixo',
    headCreated: 'Criada em',
    headLastUsed: 'Último uso',
    headActions: 'Ações',
    docsLink: 'Veja a documentação para exemplos de uso.',
  },
  settings: {
    title: 'Configurações',
    emailLabel: 'E-mail da conta',
    passwordTitle: 'Alterar senha',
    newPasswordLabel: 'Nova senha',
    confirmPasswordLabel: 'Confirmar nova senha',
    savePassword: 'Salvar nova senha',
    successNotice: 'Senha atualizada com sucesso.',
    mismatchError: 'As senhas não coincidem ou são muito curtas (mínimo 8 caracteres).',
    genericError: 'Não foi possível atualizar a senha.',
    signOut: 'Encerrar sessão',
  },
}
